services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:///app.db
      - THRESH_AUTH=0.15
      - THRESH_SYN=0.70
      - MAX_IMAGE_MB=8
      - LOG_LEVEL=INFO
    volumes:
      - backend_data:/app/data
      - model_artifacts:/app/app/pipeline/artifacts
    networks:
      - catalogai_network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000
      - NODE_ENV=development
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - catalogai_network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  model_artifacts:
    driver: local

networks:
  catalogai_network:
    driver: bridge