FROM node:20-alpine

WORKDIR /app

# Copy and install
COPY package.json ./
RUN npm install

# Copy source
COPY . .

# Run dev server
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]